global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'php-fpm'
    static_configs:
      - targets: ['php-fpm-exporter:9253']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 
  
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
